(defun area-of-rectangle (length breadth)
  (* length breadth))

(defun area-of-circle (radius)
  (* pi radius radius))

(defun area-of-triangle (base height)
  (* 0.5 base height))

(defun run-area ()
  (format t "~%=== Area Calculator ===~%")
  (format t "1. Rectangle~%")
  (format t "2. Circle~%")
  (format t "3. Triangle~%")
  (format t "Choose a shape (1/2/3): ")
  (finish-output)
  (let ((choice (parse-integer (read-line))))
    (cond
      ((= choice 1)
       (format t "Enter Length: ")
       (finish-output)
       (let ((l (parse-integer (read-line))))
         (format t "Enter Breadth: ")
         (finish-output)
         (let ((b (parse-integer (read-line))))
           (format t "Area of Rectangle = ~A~%" (area-of-rectangle l b)))))
      ((= choice 2)
       (format t "Enter Radius: ")
       (finish-output)
       (let ((r (parse-integer (read-line))))
         (format t "Area of Circle = ~A~%" (area-of-circle r))))
      ((= choice 3)
       (format t "Enter Base: ")
       (finish-output)
       (let ((base (parse-integer (read-line))))
         (format t "Enter Height: ")
         (finish-output)
         (let ((h (parse-integer (read-line))))
           (format t "Area of Triangle = ~A~%" (area-of-triangle base h)))))
      (t
       (format t "Invalid choice!~%")))))