(defun fibonacci (n)
  (let ((a 0) (b 1))
    (format t "Fibonacci Series up to ~A terms:~%" n)
    (dotimes (i n)
      (format t "~A " a)
      (let ((temp (+ a b)))
        (setf a b)
        (setf b temp)))
    (terpri)))

(defun run-fibonacci ()
  (format t "Enter the number of terms: ")
  (finish-output)
  (let ((n (parse-integer (read-line))))
    (fibonacci n)))